theme = "ayu_mirage"

[editor]
true-color = true
line-number = "relative"
color-modes = true
bufferline = "multiple"
cursorline = true
shell = ["nu", "-c"]

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-base-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "register", "file-type", "position", "position-percentage", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true

[keys.normal]
C-s = ":w"

[keys.insert]
j = {k = "normal_mode"}
